#!/usr/bin/env bash
# ==============================================================================
# core/config.sh - EULA, server.properties, and lifecycle management scripts
# ==============================================================================

# Accept Minecraft EULA
setup_eula() {
    local server_dir="$1"
    echo "# By changing the setting below to TRUE you are indicating your agreement to our EULA (https://aka.ms/MinecraftEULA)." > "${server_dir}/eula.txt"
    echo "eula=true" >> "${server_dir}/eula.txt"
    log_success "EULA aceptado automáticamente (eula=true)."
}

# Generate or update server.properties
setup_server_properties() {
    local server_dir="$1"
    local port="${2:-25565}"
    local motd="${3:-A Minecraft Server created with MC-Server-Creator}"
    local online_mode="${4:-true}"
    local difficulty="${5:-easy}"
    local gamemode="${6:-survival}"
    local max_players="${7:-20}"
    local pvp="${8:-true}"

    local prop_file="${server_dir}/server.properties"

    cat > "$prop_file" << EOF
# Minecraft Server Properties
# Generated by mc-server-creator on $(date)
server-port=${port}
motd=${motd}
online-mode=${online_mode}
difficulty=${difficulty}
gamemode=${gamemode}
max-players=${max_players}
pvp=${pvp}
enable-command-block=true
spawn-protection=0
view-distance=10
simulation-distance=8
allow-flight=true
white-list=false
enable-rcon=false
EOF

    log_success "Configuración server.properties generada (Puerto: $port, Online-mode: $online_mode)."
}

# Generate start.sh, stop.sh, console.sh, and backup.sh
setup_runtime_scripts() {
    local server_dir="$1"
    local server_name="$2"
    local ram_mb="$3"
    local java_bin="$4"
    local jar_name="${5:-server.jar}"
    local session_name="mc-${server_name}"

    # Generate Aikar's flags if RAM >= 3000MB, otherwise balanced G1GC flags
    local jvm_flags="-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch"

    # 1. start.sh
    cat > "${server_dir}/start.sh" << EOF
#!/usr/bin/env bash
cd "\$(dirname "\$0")"

SESSION="${session_name}"

if screen -list | grep -q "[0-9]*\.\${SESSION}\s"; then
    echo "⚠ El servidor ya está en ejecución en la sesión screen '\${SESSION}'."
    echo "Usa ./console.sh para acceder a la consola."
    exit 1
fi

echo "Iniciando servidor de Minecraft '\${SESSION}' con ${ram_mb}MB de RAM..."
screen -dmS "\${SESSION}" bash -c "\"${java_bin}\" -Xms1024M -Xmx${ram_mb}M ${jvm_flags} -jar \"${jar_name}\" nogui"

sleep 2
if screen -list | grep -q "[0-9]*\.\${SESSION}\s"; then
    echo "✔ Servidor iniciado exitosamente en segundo plano."
    echo "👉 Usa './console.sh' para ver la consola."
    echo "👉 Usa './stop.sh' para detener el servidor."
else
    echo "✖ Error al iniciar el servidor. Revisa los logs o inicia manualmente:"
    echo "\"${java_bin}\" -Xms1024M -Xmx${ram_mb}M -jar \"${jar_name}\" nogui"
fi
EOF

    # 2. stop.sh
    cat > "${server_dir}/stop.sh" << EOF
#!/usr/bin/env bash
SESSION="${session_name}"

if ! screen -list | grep -q "[0-9]*\.\${SESSION}\s"; then
    echo "⚠ El servidor no está en ejecución."
    exit 0
fi

echo "Deteniendo servidor '\${SESSION}' de forma segura..."
screen -S "\${SESSION}" -X stuff "say El servidor se detendrá en 5 segundos...$(printf '\r')"
sleep 2
screen -S "\${SESSION}" -X stuff "save-all$(printf '\r')"
sleep 2
screen -S "\${SESSION}" -X stuff "stop$(printf '\r')"

echo "Esperando a que el servidor guarde los mundos y cierre..."
for i in {1..15}; do
    if ! screen -list | grep -q "[0-9]*\.\${SESSION}\s"; then
        echo "✔ Servidor detenido completamente."
        exit 0
    fi
    sleep 1
done

echo "⚠ El servidor tardó en responder. Verificando estado con 'screen -list'."
EOF

    # 3. console.sh
    cat > "${server_dir}/console.sh" << EOF
#!/usr/bin/env bash
SESSION="${session_name}"

if ! screen -list | grep -q "[0-9]*\.\${SESSION}\s"; then
    echo "⚠ El servidor no está en ejecución. Inícialo primero con './start.sh'."
    exit 1
fi

echo "================================================================="
echo " Conectando a la consola del servidor de Minecraft."
echo " 👉 IMPORTANTE: Para salir sin apagar el server: presiona Ctrl+A y luego D."
echo "================================================================="
sleep 1
screen -r "\${SESSION}"
EOF

    # 4. backup.sh
    cat > "${server_dir}/backup.sh" << EOF
#!/usr/bin/env bash
cd "\$(dirname "\$0")"
BACKUP_DIR="backups"
TIMESTAMP=\$(date +"%Y%m%d_%H%M%S")
BACKUP_FILE="\${BACKUP_DIR}/backup_\${TIMESTAMP}.tar.gz"

mkdir -p "\$BACKUP_DIR"
echo "Creando copia de seguridad del servidor..."

# Check if server is running, if so, send save-off and save-all
SESSION="${session_name}"
if screen -list | grep -q "[0-9]*\.\${SESSION}\s"; then
    screen -S "\${SESSION}" -X stuff "save-off$(printf '\r')"
    screen -S "\${SESSION}" -X stuff "save-all$(printf '\r')"
    sleep 2
fi

tar --exclude="\$BACKUP_DIR" --exclude="*.jar" --exclude="libraries" -czf "\$BACKUP_FILE" .

if screen -list | grep -q "[0-9]*\.\${SESSION}\s"; then
    screen -S "\${SESSION}" -X stuff "save-on$(printf '\r')"
fi

echo "✔ Backup completado con éxito: \$BACKUP_FILE"
EOF

    chmod +x "${server_dir}/start.sh" "${server_dir}/stop.sh" "${server_dir}/console.sh" "${server_dir}/backup.sh"
    log_success "Scripts de ejecución creados (start.sh, stop.sh, console.sh, backup.sh)."
}
